SocialMedia/Models/Grupo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SocialMedia.Models
{
    [Table("Grupos")]
    public class Grupo : BaseModel
    {

        [Required(ErrorMessage = "Campo obrigatório!")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public string Descricao { get; set; }

        public string imagem { get; set; }

        public User user { get; set; }

        public List<InscricoesGrupos> inscricoesGrupos { get; set; }


    }
}

SocialMedia/Controllers/GrupoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SocialMedia.DAL;
using SocialMedia.Models;

namespace SocialMedia.Controllers
{
    public class GrupoController : Controller
    {
        private readonly GrupoDAO _grupoDAO;
        private readonly PostDAO _postDAO;
        private readonly UserDAO _userDAO;
        private readonly InscricoesGruposDAO _inscricoesGruposDAO;
        private readonly IWebHostEnvironment _hosting;

        public GrupoController(GrupoDAO grupoDAO, IWebHostEnvironment hosting, UserDAO userDAO, InscricoesGruposDAO inscricoesGrupos, PostDAO postDAO)
        {
            _userDAO = userDAO;
            _hosting = hosting;
            _grupoDAO = grupoDAO;
            _postDAO = postDAO;
            _inscricoesGruposDAO = inscricoesGrupos;
        }

        // GET: Grupo
        public IActionResult Index()
        {
            string id = HttpContext.Session.GetString("id");

            if (id == null)
            {
                return RedirectToAction("Index", "User");
            }
            List<Grupo> grupos = _grupoDAO.Listar();
           
            ViewBag.Quantidade = grupos.Count;
            ViewBag.userId = Convert.ToInt32(HttpContext.Session.GetString("id"));
            return View(grupos);
        }
        public IActionResult mygroups()
        {
            ViewBag.subscriptions =  _inscricoesGruposDAO.getAllSubscriptions(Convert.ToInt32(HttpContext.Session.GetString("id")));
            return View();
        }

        public IActionResult registerPostGroup()

        {
            ViewBag.name = HttpContext.Session.GetString("name");
            ViewBag.image = HttpContext.Session.GetString("image");
            ViewBag.subscriptions = _inscricoesGruposDAO.getAllSubscriptions(Convert.ToInt32(HttpContext.Session.GetString("id")));
            return View();
        }

        public IActionResult registerPost(string description, string image, IFormFile file)
        {
            string id = HttpContext.Session.GetString("id");
            string groupId = HttpContext.Session.GetString("groupId");
            User user = _userDAO.findById(Convert.ToInt32(id));

            if (file != null)
            {
                string archive = $"{ Guid.NewGuid()}{Path.GetExtension(file.FileName)}";
                string path = Path.Combine(_hosting.WebRootPath, "images", archive);
                file.CopyTo(new FileStream(path, FileMode.Create));
                image = archive;
            }
            else
            {
                image = "no-image.png";

            }
            Post post = new Post
            {
                title = "123",
                description = description,
                image = image,
                user = user,
                grupo = _grupoDAO.BuscarPorId(Convert.ToInt32(groupId))
            };

            _postDAO.CreatePost(post);
            return RedirectToAction("Details", "Grupo");
        }

        public IActionResult rejectedSubscription(int Id)
        {
            InscricoesGrupos inscricoesGrupos = _inscricoesGruposDAO.findById(Id);
            inscricoesGrupos.status = "rejected";
            _inscricoesGruposDAO.updateSubscription(inscricoesGrupos);
            return RedirectToAction("mygroups", "Grupo");
        }
        public IActionResult acceptSubscription(int Id)
        {
            InscricoesGrupos inscricoesGrupos = _inscricoesGruposDAO.findById(Id);
            inscricoesGrupos.status = "accept";
            _inscricoesGruposDAO.updateSubscription(inscricoesGrupos);
            return RedirectToAction("mygroups", "Grupo");
        }
        public IActionResult verify(int Id)
        {
            if (_inscricoesGruposDAO.verifyGroupSubscriptions(Convert.ToInt32(HttpContext.Session.GetString("id")), Id))
            {
                ViewBag.name = HttpContext.Session.GetString("name");
                ViewBag.image = HttpContext.Session.GetString("image");
                HttpContext.Session.SetString("groupId", Id.ToString());
                ViewBag.groupId = Id;
                ViewBag.grupo = _postDAO.findPostsByGroupId(Id);
                return RedirectToAction("Details", "Grupo");
            }
            else
            {
                return RedirectToAction("Index", "Grupo");
            }
        }

        // GET: Grupo/Details/5
        public IActionResult Details()
        {
            ViewBag.name = HttpContext.Session.GetString("name");
            ViewBag.image = HttpContext.Session.GetString("image");

            ViewBag.groupId = Convert.ToInt32(HttpContext.Session.GetString("groupId"));
            ViewBag.grupo = _postDAO.findPostsByGroupId(Convert.ToInt32(HttpContext.Session.GetString("groupId")));
            return View();
         
        }

        // GET: Grupo/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Grupo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Grupo grupo, IFormFile file)
        {
            if (ModelState.IsValid)

            {
                if (file != null)
                {
                    string arquivo = $"{Guid.NewGuid()}{Path.GetExtension(file.FileName)}";
                    string caminho = Path.Combine(_hosting.WebRootPath, "images", arquivo);
                    file.CopyTo(new FileStream(caminho, FileMode.CreateNew));
                    grupo.imagem = arquivo;
                }
                else
                {
                    grupo.imagem = "semimagem.gif";
                }

                grupo.user = _userDAO.findById(Convert.ToInt32(HttpContext.Session.GetString("id")));

                if (_grupoDAO.Cadastrar(grupo))
                {
                    return RedirectToAction("Index", "Grupo");
                }
            }
                ModelState.AddModelError("", "Não foi possível cadastradar o grupo!");
                return View(grupo);
        }

        // GET: Grupo/Edit/5
        public IActionResult Edit(int id)
        {
            
            ViewBag.grupo = _grupoDAO.BuscarPorId(id);
            return View();
        }

        // POST: Grupo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Grupo grupo, IFormFile file)
        {
            if (file != null)
            {
                string arquivo = $"{Guid.NewGuid()}{Path.GetExtension(file.FileName)}";
                string caminho = Path.Combine(_hosting.WebRootPath, "images", arquivo);
                file.CopyTo(new FileStream(caminho, FileMode.CreateNew));
                grupo.imagem = arquivo;
            }
            _grupoDAO.Alterar(grupo);
            ViewBag.grupo = grupo;
            return RedirectToAction("Index", "Grupo");
        }

        // GET: Grupo/Delete/5
        public IActionResult Delete(int id)
        {
            return View(_grupoDAO.BuscarPorId(id));
        }

        // POST: Grupo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _grupoDAO.Remover(id);
            return RedirectToAction("Index", "Grupo");
        }

      
    }
}

SocialMedia/Controllers/PostCommentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SocialMedia.DAL;
using SocialMedia.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SocialMedia.Controllers
{
    public class PostCommentController : Controller
    {
        private readonly PostCommentDAO _postCommentDAO;
        private readonly PostDAO _postDAO;
        private readonly UserDAO _userDAO;


        public PostCommentController(PostCommentDAO postCommentDAO, PostDAO postDAO, UserDAO userDAO)
        {

            _postCommentDAO = postCommentDAO;
            _postDAO = postDAO;
            _userDAO = userDAO;



        }
        public IActionResult createPostComment(int postId, string description)
        {
            Post post =_postDAO.findPostById(postId);
           
            User user = _userDAO.findById(Convert.ToInt32(HttpContext.Session.GetString("id")));

            PostComments postComments = new PostComments { 
                description = description,
                user = user,
                post = post
            };
            _postCommentDAO.createPostComment(postComments);

            if (post.grupo != null)
            {
                return RedirectToAction("Details", "Grupo");
            }
            else
            {
                return RedirectToAction("HomePage", "HomePage");
            }

           

           

        }
    }
}

SocialMedia/Views/Grupo/Create.cshtml
@model SocialMedia.Models.Grupo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link type="text/css" rel="stylesheet" href="~/css/registerPage.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;1,300&display=swap" rel="stylesheet">

</head>
<body>

    <header><embed src="~/assets/arrow_back.svg" /><a asp-action="Index" asp-controller="Grupo">Voltar</a><h2>Grupo</h2></header>

    <header><embed src="~/assets/arrow_back.svg" /><a asp-action="" asp-controller="Grupo">Voltar</a><h2>Grupo</h2></header>

<main>
    <form asp-action="Create" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-container">
            <div class="first-line">
                <div class="inputs-container">
                    <label asp-for="Nome" class="standard-label"></label>
                    <input asp-for="Nome" class="basic-input" />
                    <span asp-validation-for="Nome"></span>
                </div>
            </div>
            <div class="second-line">
                <div class="inputs-container">
                    <label asp-for="Descricao" class="standard-label"></label>
                    <input asp-for="Descricao" class="basic-input" />
                    <span asp-validation-for="Descricao"></span>
                </div>
            </div>
            <div class="third-line">
                <div id="imagem" class="form-group">
                    <label asp-for="imagem">Imagem:</label>
                    <input type="file" class="form-control-file" name="file" />
                </div>

            </div>
            <input type="submit" value="Criar" class="finish-button" />
        </div>
   
    </form>
    
</main>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

SocialMedia/Views/Grupo/Delete.cshtml
@model SocialMedia.Models.Grupo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Você tem certeza que deseja excluir este grupo?</h3>
<div>
    <h4>Grupo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.imagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.imagem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

SocialMedia/Views/Grupo/Details.cshtml
@using SocialMedia.Models;
@using Microsoft.AspNetCore.Http;
@{
    List<Post> posts = ViewBag.grupo;


}

<!DOCTYPE html>
<html>

<head>
    <title>Social Media</title>

    <link type="text/css" rel="stylesheet" href="~/css/HomePage.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;1,300&display=swap"
          rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;1,300&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>

<body>

    <main>
        <div class="left-content">
            <div class="menu-items-container">
                <div class="menu-item">
                    <svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24" viewBox="0 0 24 24" width="24"><g><rect fill="none" height="24" width="24" /><rect fill="none" height="24" width="24" /></g><g class="svg-color"><path d="M19,9.3V5c0-0.55-0.45-1-1-1h-1c-0.55,0-1,0.45-1,1v1.6l-3.33-3c-0.38-0.34-0.96-0.34-1.34,0l-8.36,7.53 C2.63,11.43,2.84,12,3.3,12H5v7c0,0.55,0.45,1,1,1h3c0.55,0,1-0.45,1-1v-5h4v5c0,0.55,0.45,1,1,1h3c0.55,0,1-0.45,1-1v-7h1.7 c0.46,0,0.68-0.57,0.33-0.87L19,9.3z M10,10c0-1.1,0.9-2,2-2s2,0.9,2,2H10z" /></g></svg>
                    <a asp-action="HomePage" asp-controller="HomePage">Página inicial</a>

                </div>

                <div class="menu-item">

                    <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path d="M0 0h24v24H0V0z" fill="none" /><path class="svg-color" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 3c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3zm0 14.2c-2.5 0-4.71-1.28-6-3.22.03-1.99 4-3.08 6-3.08 1.99 0 5.97 1.09 6 3.08-1.29 1.94-3.5 3.22-6 3.22z" /></svg>
                    <a asp-action="UserProfile" asp-controller="User">Meu perfil</a>

                </div>
                <div class="menu-item">

                    <svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24" viewBox="0 0 24 24" width="24"><rect fill="none" height="24" width="24" /><g class="svg-color"><path d="M12,12.75c1.63,0,3.07,0.39,4.24,0.9c1.08,0.48,1.76,1.56,1.76,2.73L18,17c0,0.55-0.45,1-1,1H7c-0.55,0-1-0.45-1-1l0-0.61 c0-1.18,0.68-2.26,1.76-2.73C8.93,13.14,10.37,12.75,12,12.75z M4,13c1.1,0,2-0.9,2-2c0-1.1-0.9-2-2-2s-2,0.9-2,2 C2,12.1,2.9,13,4,13z M5.13,14.1C4.76,14.04,4.39,14,4,14c-0.99,0-1.93,0.21-2.78,0.58C0.48,14.9,0,15.62,0,16.43L0,17 c0,0.55,0.45,1,1,1l3.5,0v-1.61C4.5,15.56,4.73,14.78,5.13,14.1z M20,13c1.1,0,2-0.9,2-2c0-1.1-0.9-2-2-2s-2,0.9-2,2 C18,12.1,18.9,13,20,13z M24,16.43c0-0.81-0.48-1.53-1.22-1.85C21.93,14.21,20.99,14,20,14c-0.39,0-0.76,0.04-1.13,0.1 c0.4,0.68,0.63,1.46,0.63,2.29V18l3.5,0c0.55,0,1-0.45,1-1L24,16.43z M12,6c1.66,0,3,1.34,3,3c0,1.66-1.34,3-3,3s-3-1.34-3-3 C9,7.34,10.34,6,12,6z" /></g></svg>
                    <a asp-controller="Grupo" asp-action="">Grupos</a>

                </div>

                <div class="menu-item">

                    <svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24" viewBox="0 0 24 24" width="24"><rect fill="none" height="24" width="24" /><g class="svg-color"><path d="M12,12.75c1.63,0,3.07,0.39,4.24,0.9c1.08,0.48,1.76,1.56,1.76,2.73L18,17c0,0.55-0.45,1-1,1H7c-0.55,0-1-0.45-1-1l0-0.61 c0-1.18,0.68-2.26,1.76-2.73C8.93,13.14,10.37,12.75,12,12.75z M4,13c1.1,0,2-0.9,2-2c0-1.1-0.9-2-2-2s-2,0.9-2,2 C2,12.1,2.9,13,4,13z M5.13,14.1C4.76,14.04,4.39,14,4,14c-0.99,0-1.93,0.21-2.78,0.58C0.48,14.9,0,15.62,0,16.43L0,17 c0,0.55,0.45,1,1,1l3.5,0v-1.61C4.5,15.56,4.73,14.78,5.13,14.1z M20,13c1.1,0,2-0.9,2-2c0-1.1-0.9-2-2-2s-2,0.9-2,2 C18,12.1,18.9,13,20,13z M24,16.43c0-0.81-0.48-1.53-1.22-1.85C21.93,14.21,20.99,14,20,14c-0.39,0-0.76,0.04-1.13,0.1 c0.4,0.68,0.63,1.46,0.63,2.29V18l3.5,0c0.55,0,1-0.45,1-1L24,16.43z M12,6c1.66,0,3,1.34,3,3c0,1.66-1.34,3-3,3s-3-1.34-3-3 C9,7.34,10.34,6,12,6z" /></g></svg>
                    <a asp-controller="Grupo" asp-action="mygroups">Meus Grupos</a>

                </div>
            </div>


        </div>

        <div class="center-content">
            <div class="create-post-container">
                <div class="user-image-and-name">
                    <img src="~/UserImages/@ViewBag.image" />
                    <span>@ViewBag.name</span>
                </div>
                <form asp-action="registerPost" asp-controller="Grupo" method="post" 
                      enctype="multipart/form-data">
                    <div class="input-container">
                        <textarea placeholder="O que está acontecendo?" name="description"></textarea>
                        <input type="file" name="file" />
                    </div>

                    <button type="submit" class="publish-button" value="@ViewBag.groupId">Publicar</button>
                </form>

            </div>
            <div class="post-container">
                @foreach (Post registerPosts in posts)
                {
                    <div class="post-card">
                        <div class="user-image-and-name">
                            <img src="~/UserImages/@registerPosts.user.image" />
                            <span>@registerPosts?.user?.name</span>

                        </div>
                        <img src="~/images/@registerPosts.image" alt="" class="post-image" style="width:100%; object-fit:cover" />

                        <div class="description">
                            <p> @registerPosts.description</p>
                        </div>

                        <div class="new-comment">
                            <img src="~/UserImages/@registerPosts.user.image" />
                            <form asp-action="createPostComment" asp-controller="PostComment">

                                <span>@ViewBag.name</span>

                                <textarea placeholder="Faça um comentário..." name="description"></textarea>
                                <button type="submit" name="postId" value="@registerPosts.Id">Comentar</button>
                            </form>

                        </div>

                        @for (int i = 0; i < registerPosts.postComments.Count; i++)
                        {
                            <div class="new-comment reply">
                                <img src="~/UserImages/@registerPosts.postComments[i].user.image" />
                                <form>

                                    <span>@registerPosts.postComments[i].user.name</span>

                                    <p>@registerPosts.postComments[i].description</p>

                                </form>

                            </div>
                        }



                    </div>
                }



            </div>
        </div>
        <div class="right-content">



        </div>
    </main>
</body>


</html>
<script>

    var url = "http://servicodados.ibge.gov.br/api/v3/noticias/?qtd=100";




    fetch(url, { method: "GET" })
        .then(response => response.json())
        .then(json => {








            for (i = 0; i < 10; i++) {
                let number = Math.floor(Math.random() * 100)
                let mainDiv = document.createElement('div')

                mainDiv.className = "small-releases"


                let newDiv = document.createElement('div')
                newDiv.className = "photo-and-link"


                var h3 = document.createElement("h3");
                var obj = $.parseJSON(json.items[number].imagens)


                var a = document.createElement("a");
                var image = document.createElement("img");

                newDiv.append(a,image)

                image.src = "https://agenciadenoticias.ibge.gov.br/" + obj.image_intro;

                h3.innerHTML = json.items[number].titulo
                a.innerHTML = json.items[number].introducao

                a.href = json.items[number].link

                mainDiv.append(h3, newDiv)

                $(".right-content").append(mainDiv)




            }
        })
        .catch(error => console.log(error));
</script>

SocialMedia/Views/Grupo/Edit.cshtml
@model SocialMedia.Models.Grupo
@using SocialMedia.Models

@{
    Grupo grupo = ViewBag.grupo;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Grupo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            
            <div id="imagem" class="form-group">
                <label asp-for="imagem">Imagem:</label>
                <img src="~/images/@grupo?.imagem" alt="" class="post-image" style="width:100%; object-fit:cover" />
                <input type="file" class="form-control-file" name="file" />
            </div>

                <input type="hidden" asp-for="Id" />

                <div class="form-group">
                    <input type="submit" value="Save" />
                </div>
            </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

SocialMedia/Views/Grupo/Index.cshtml
@model IEnumerable<SocialMedia.Models.Grupo>


@{
    Layout = null;

}

<!DOCTYPE html>

<html>
<head>
    <title>Grupos</title>
    <link type="text/css" rel="stylesheet" href="~/css/groupIndex.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;1,300&display=swap"
          rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;1,300&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <main>
        <div class="left-content">
            <div class="menu-items-container">
                <div class="menu-item">
                    <a asp-controller="HomePage" asp-action="HomePage">Página inicial</a>
                </div>

                <div class="menu-item">
                    <a asp-action="Create">Novo Grupo</a>
                </div>
            </div>

        </div>

        <div class="center-content">
            @foreach (var item in Model)
            {
                


            <div class="group-card">
                <img src="~/images/@item.imagem"
                     alt="@item.Descricao" />

                <div class="group-informations">
                    <h3> @Html.DisplayFor(modelItem => item.Nome)</h3>
                    <p> @Html.DisplayFor(modelItem => item.Descricao)</p>
                    <div class="subscriptions-and-author-informations">

                        @{
                            string valor;

                            if (item.user.Id == ViewBag.userId)
                            {
                                valor = "Entrar";
                            }
                            else
                            {
                                if (item.inscricoesGrupos.Find(x => x.user.Id == ViewBag.userId && x.status == "accept") != null)
                                {

                                    valor = "Entrar";
                                }
                                else if (item.inscricoesGrupos.Find(x => x.user.Id == ViewBag.userId && x.status == "pending") != null)
                                {

                                    valor = "Solicitado";
                                }
                                else
                                {
                                    valor = "inscrever-se";
                                }
                            }

                        }
                        <span>@item.user.name</span> <a asp-action="verify" asp-route-id="@item.Id">@valor</a>
                    </div>
                </div>

            </div>
                
            }
        </div>
        <div class="right-content">

        </div>
    </main>
</body>
</html>
<script>

    var url = "http://servicodados.ibge.gov.br/api/v3/noticias/?qtd=100";




    fetch(url, { method: "GET" })
        .then(response => response.json())
        .then(json => {








            for (i = 0; i < 10; i++) {
                let number = Math.floor(Math.random() * 100)
                let mainDiv = document.createElement('div')

                mainDiv.className = "small-releases"


                let newDiv = document.createElement('div')
                newDiv.className = "photo-and-link"


                var h3 = document.createElement("h3");
                var obj = $.parseJSON(json.items[number].imagens)


                var a = document.createElement("a");
                var image = document.createElement("img");

                newDiv.append(a,image)

                image.src = "https://agenciadenoticias.ibge.gov.br/" + obj.image_intro;

                h3.innerHTML = json.items[number].titulo
                a.innerHTML = json.items[number].introducao

                a.href = json.items[number].link

                mainDiv.append(h3, newDiv)

                $(".right-content").append(mainDiv)




            }
        })
        .catch(error => console.log(error));
</script>